# Generated by Django 5.2.5 on 2025-08-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("area_terreno", models.FloatField(default=0.0)),
                ("area_privativa", models.FloatField(default=0.0)),
                ("num_unidades", models.IntegerField(default=1)),
                ("custos_config", models.JSONField(default=dict)),
                ("etapas_percentuais", models.JSONField(default=dict)),
                ("custos_indiretos_percentuais", models.JSONField(default=dict)),
                ("custos_indiretos_fixos", models.JSONField(default=dict)),
                ("custos_indiretos_obra", models.JSONField(default=dict)),
                ("duracao_obra", models.IntegerField(default=12)),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="Pavimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("rep", models.IntegerField(default=1)),
                ("coef", models.FloatField(default=1.0)),
                ("area", models.FloatField(default=0.0)),
                ("constr", models.BooleanField(default=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pavimentos",
                        to="viabilidade.projeto",
                    ),
                ),
            ],
        ),
    ]
