# Generated by Django 5.2.5 on 2025-08-23 23:51

import viabilidade.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viabilidade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="analise_ia",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="custos_config",
            field=models.JSONField(default=viabilidade.models.default_custos_config),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="custos_indiretos_fixos",
            field=models.JSONField(
                default=viabilidade.models.default_custos_indiretos_fixos
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="custos_indiretos_obra",
            field=models.JSONField(
                default=viabilidade.models.default_custos_indiretos_obra
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="custos_indiretos_percentuais",
            field=models.JSONField(
                default=viabilidade.models.default_custos_indiretos_percentuais
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="etapas_percentuais",
            field=models.JSONField(
                default=viabilidade.models.default_etapas_percentuais
            ),
        ),
    ]
