name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Show migrations plan
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la "$GITHUB_WORKSPACE"
          find "$GITHUB_WORKSPACE" -maxdepth 3 -type f -name manage.py -print || true
          python3 "$GITHUB_WORKSPACE/manage.py" showmigrations --plan

      - name: Apply migrations
        run: python3 "$GITHUB_WORKSPACE/manage.py" migrate --noinput

      - name: Run tests
        run: python3 "$GITHUB_WORKSPACE/manage.py" test --verbosity=2
